## DX@Scale CI/CD Template for Azure Pipelines
#-----------------------------------------------------------------------------------------------------------
# Maintained by @ramesh-karanji(Ramesh Karanji)
# Follows reference pipeline available at docs.dxatscale.io
# 
#------------------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit
#
# Prepare a pool of CI scratch orgs

name: 'Replenish CI Pools - Auto Triggered'
trigger: none
pr: none

# Trigger Schedule
schedules:
    - cron: '0 0 * * *'
      displayName: Daily midnight prepare pool
      branches:
          include:
              - azp-templates
      always: true

# Runs build on the mentioned Image    
pool:
    vmImage: 'ubuntu-latest'

#The docker container contains sfpowerscripts and the dependencies it needs to run, # refer to https://hub.docker.com/r/dxatscale/sfpowerscripts                
container: dxatscale/sfpowerscripts:latest

#Custom Variables
variables:
  - group: CICD

steps:    
# Authenticate DevHub 
    - script: |
          echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub
      displayName: 'Authenticate DevHub'

    - task: DownloadSecureFile@1
      name: npmrc
      inputs:
          secureFile: .npmrc

    - task: npmAuthenticate@0
      inputs:
        workingFile: $(npmrc.secureFilePath)

## Scratch Org Pool creation  for CI 

    - script: |
          sfdx sfpowerscripts:orchestrator:prepare -f config/cipool.json -v devhub --npmrcpath $(npmrc.secureFilePath)
      displayName: 'Prepare a pool of scratch orgs'

#Publish logs to artifacts             
    - task: PublishBuildArtifacts@1
      inputs:
            pathToPublish: .sfpowerscripts/prepare_logs/
            artifactName: PrepareLogs