# ██████████   █████ █████  █████████   █████████                     ████
#░░███░░░░███ ░░███ ░░███  ███░░░░░░   ███░░░░░███                   ░░███
#  ███   ░░███ ░░███ ███  ░███ ██████ ░███    ░░░   ██████   ██████   ░███   ██████
# ░███    ░███  ░░█████   ░███░███░███░░█████████  ███░░███ ░░░░░███  ░███  ███░░███
# ░███    ░███   ███░███  ░███░███░███ ░░░░░░░░███░███ ░░░   ███████  ░███ ░███████
# ░███    ███   ███ ░░███ ░███░░░ ░███ ███    ░███░███  ███ ███░░███  ░███ ░███░░░
# ██████████   █████ █████░░█████████ ░░█████████ ░░██████ ░░████████ █████░░██████
# ░░░░░░░░░░   ░░░░░ ░░░░░  ░░░░░░░░░   ░░░░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░
# 
# DX@Scale CI/CD Template for Azure Pipelines
#-----------------------------------------------------------------------------------------------------------
# Maintained by @ramesh-karanji(Ramesh Karanji)
# Follows reference pipeline available at docs.dxatscale.io
# 
#------------------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is opened with 
# one of the specified target branches, or when updates are made to such a pull request.
#
# This template will be triggered whenever a Pull request is raised against the main branch...
#
#
#
# --- To report metrics about the pipeline to datadog or newrelic, set these variables in CICD group
#
#  #SFPOWERSCRIPTS_NEWRELIC: 'true'
#  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '<NEWRELIC_INSIGHT_INSERT_KEYS>'
# 
#  or if you are using Datadog
#  #SFPOWERSCRIPTS_DATADOG: 'true'
#  #SFPOWERSCRIPTS_DATADOG_HOST: '<DATADOG-HOST>'
#  #SFPOWERSCRIPTS_DATADOG_API_KEY: '<DATADOG-API-KEY>'
#
# or if you are using a Hosted StatsD server
#  
#  # SFPOWERSCRIPTS_STATSD: 'true'
#  # SFPOWERSCRIPTS_STATSD_HOST: '<STATSD_HOST_IP>'
#
# --------------------------------------------------------------------------------------------------------


name: 'PR Validation - Auto Triggered'

# Build pushes to main so we can release merged changes
trigger: none

# Build pull requests so we can test them
pr:
    autoCancel: false
    drafts: false
    branches:
        include:
            - main

#Custom Variables
variables:
  - group: CICD

#Stages to run as part Validate
stages:
    - stage: ValidatePMD
#This Stage will run static analysis of the apex classes and triggers using PMD      
      displayName: ValidatePMD
      dependsOn: []
      jobs:
          - job: ValidatePMD
            displayName: 'Validate PMD'
# Runs build on the mentioned Image                           
            pool:
                vmImage: 'ubuntu-latest'

#The docker container contains sfpowerscripts and the dependencies it needs to run, # refer to https://github.com/orgs/dxatscale/packages/container/package/sfpowerscripts                
            container: ghcr.io/dxatscale/sfpowerscripts:latest         

            steps:

            - checkout: self
              persistCredentials: true

#This task is used to run a static analysis of the apex classes and triggers using PMD      
            - script: |
                  sfdx sfpowerscripts:analyze:pmd -b  -o pmd-output --format=csv 
              continueOnError: true
              displayName: 'PMD Validation'  

#Publish PMD analysis results to artifacts
            - task: PublishBuildArtifacts@1
              inputs:
                    pathToPublish: pmd-output
                    artifactName: PMDResults


    - stage: ValidateSource
#Validates Source code changes 
      displayName: 'Validate Source'
      dependsOn: []
      jobs:
          - job: ValidateSource
            displayName: 'Validate Source'
# Runs build on the mentioned Image               
            pool:
                vmImage: 'ubuntu-latest'

#The docker container contains sfpowerscripts and the dependencies it needs to run, 
# refer to https://github.com/orgs/dxatscale/packages/container/package/sfpowerscripts             

            container: ghcr.io/dxatscale/sfpowerscripts:latest     

            steps:

            - checkout: self
              persistCredentials: true

# Authenticate DevHub                
            - script: |
                    echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
                    sfdx auth:sfdxurl:store -f authfile -a devhub
              displayName: 'Authenticate DevHub'

#Validate the incoming change against a prepared scratch org fetched from the provided CI pools 
# and marks Scratch Org for deletion
            - script: |
                    sfdx sfpowerscripts:orchestrator:validate -x -p ci -v devhub --loglevel debug
              displayName: 'Validate Source'
