# Return an used scratch org back to the pool for replenishment

name: 'Scratch Org Recycler - User Triggered'

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Username of the scratch org"
        required: true

jobs:

  delete-scracthorg:
    name: 'Return a used scratch org to the pool ${{ github.event.inputs.username }}'
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts
    env:
      #SET ONE OF THESE FOR METRICS
      #SFPOWERSCRIPTS_NEWRELIC: 'true'
      #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INGEST_KEY }}'
      #SFPOWERSCRIPTS_DATADOG: 'true'
      #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
      #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'
    steps:


      - name: 'Authenticate Dev Hub'
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub

      - name: 'Delete scratch org ${{ github.event.inputs.username }}'
        run: 'sfdx sfpowerscripts:pool:org:delete -u ${{ github.event.inputs.username }} -v devhub'
